#!/sbin/sh

	if [ -e /dev/block/mmcblk0p2 ]; then
		umount /system/sd > /dev/null 2>&1;
		set -e;
		/sbin/e2fsck /dev/block/mmcblk0p2;
		/sbin/tune2fs -c0 -i0 -j /dev/block/mmcblk0p2;
		/sbin/tune2fs -c 15 /dev/block/mmcblk0p2;
	fi;
exit 0;
