#!/sbin/sh
if [ -e /dev/block/mmcblk0p2 ]; then
	echo "" > /sys/devices/platform/usb_mass_storage/lun0/file    	
	umount /system/sd > /dev/null 2>&1;	
	mount -o rw /dev/block/mmcblk0p2 /system/sd
	mount /data > /dev/null 2>&1;
	rm -rf /system/sd/dalv* /data/dalv*
else
	echo "No ext partition found!"
	exit 1
fi
exit 0
