#!/sbin/sh
devices="/sdcard /system/sd /data"
second="/system/xbin /system/modules"
last="/system"
################
cd /
for i in $devices;
	do
		umount $i > /dev/null 2>&1;
	done
for i in $second;
	do
		umount $i > /dev/null 2>&1;
	done
for i in $last;
	do
		umount $i > /dev/null 2>&1;
	done
echo '++ all devices demounted ++'
