#!/sbin/sh
udevices="/sdcard /system/sd /data"
usecond="/system/modules /system/xbin"
ulast="/system"
mdevices="/sdcard /system /data"
mlast="/system/sd /system/sdc"
################
echo "" > /sys/devices/platform/usb_mass_storage/lun0/file
echo "++ UMS disabled for safety"
	if [ $1 -eq 0 ]; then
		for i in $udevices;
			do
				umount $i > /dev/null 2>&1;
			done
		for i in $ulast;
			do
				umount $i > /dev/null 2>&1;
			done
		for i in $usecond;
			do
				umount $i > /dev/null 2>&1;
			done
		echo '++ all devices umounted ++'
	elif [ $1 -eq 1 ]; then
		for i in $mdevices;
			do
				mount $i > /dev/null 2>&1;
			done
		for i in $mlast;
			do
				mount $i > /dev/null 2>&1;
			done
		echo '++ all devices mounted ++'
	elif [ $1 -ne 1 -a $1 -ne 0]; then
		echo "incorrect operand, $1"
		echo "please toggle using 0 or 1"
		echo "example:"
		echo "	mnt_toggle 0"
		echo "		unmounts all devices"
		echo "	mnt_toggle 1"
		echo "		mounts all devices"
		exit 1
	fi
exit 0
