#!/sbin/sh
DEVICES="/sdcard /data /system"
LAST="/system/sd /system/sdc"
################
echo "" > /sys/devices/platform/usb_mass_storage/lun0/file
for i in $DEVICES;
	do
		mount $i > /dev/null 2>&1;
	done

for i in $LAST;
	do
		mount $i > /dev/null 2>&1;
	done

echo '++ all devices mounted ++'
