#!/sbin/sh
/sbin/sh /sbin/mnt_toggle 0
	if [ "$(cat /sbin/.ums)" -eq 0 ]; then
		echo /dev/block/mmcblk0 > /sys/devices/platform/usb_mass_storage/lun0/file
		echo "enabled"
		echo "1" > /sbin/.ums
	elif [ "$(cat /sbin/.ums)" -ne 0 ]; then
		echo "" > /sys/devices/platform/usb_mass_storage/lun0/file
		echo "disabled"
		echo "0" > /sbin/.ums
	fi
